services:
  _defaults:
    autowire: true
    autoconfigure: true


  HeimrichHannot\MultiColumnEditorBundle\:
    resource: '../../{Asset,EventListener}/*'

  HeimrichHannot\MultiColumnEditorBundle\Asset\MceAssets:
    public: true